services:
  - type: web
    name: EZOHR_BACKEND
    env: node
    buildCommand: npm install
    startCommand: node index.js # Change to your entry file (e.g., node server.js or npm start)
    envVars:
      - key: PORT
        value: 10000